/home/michelle/.local/share/virtualenvs/application-povF5Wga/lib/python3.12/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.4, pluggy-1.5.0 -- /home/michelle/.local/share/virtualenvs/application-povF5Wga/bin/python
cachedir: .pytest_cache
rootdir: /home/michelle/src/home-assistant/remote-assist-display/application
configfile: pyproject.toml
plugins: asyncio-0.25.2, timeout-2.3.1, cov-6.0.0, anyio-4.8.0, flask-1.3.0
asyncio: mode=Mode.AUTO, asyncio_default_fixture_loop_scope=None
timeout: 10.0s
timeout method: signal
timeout func_only: False
collecting ... collected 2 items

tests/test_state.py::test_local_storage_set_on_url_load PASSED           [ 50%]
tests/test_state.py::test_local_storage_set_on_card_load PASSED          [100%]

=============================== warnings summary ===============================
../../../../.local/share/virtualenvs/application-povF5Wga/lib/python3.12/site-packages/_pytest/config/__init__.py:1441
  /home/michelle/.local/share/virtualenvs/application-povF5Wga/lib/python3.12/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: asyncio_fixture_loop_scope
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.04s =========================
